### ISSUE TITLE
Test precision

### ISSUE THREAD

**Issue by ShuaibZyx** [Li-Li-Whu/Point2Roof#2]
Hello, thank you very much for your excellent work. I have the following questions: 
  First of all, when I tried to use the default batch_size=1 in the test code, the program would report an error. After my search, I found that "if the batch_size is too small, the random sample may be empty, which will lead to program errors". This error can be solved by increasing the batch_size, but there is still a probability of occurrence. Second, the accuracy obtained through the test.py file is very low, is it directly related to batch_size? I cannot reproduce the results of the experiment, which makes me very confused. If you have time, can you fix this problem? Finally, how do you generate the mesh file? Thank you very much for your answer, I wish you a happy life.

**Comment by PaulLiuYZ** [comment]
> how do you generate the mesh file?
do you find the solution?

**Comment by PaulLiuYZ** [comment]
> how do you generate the mesh file?

do you find the solution?

**Comment by ZHR-rgb** [comment]
did you put the weight file to Point2Roof-master\output\pts6?
